config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # config/routes.rb
root 'pages#multi_form_page'
get '/multi_form_page', to: 'pages#multi_form_page'
post '/process_forms', to: 'pages#process_forms'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def multi_form_page
  end

  def process_forms
    redirect_to multi_form_page_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RhDemo</title>
    <!-- start ReferralHero code -->  <script>  !function(m,a,i,t,r,e){if(m.RH)return;r=m.RH={},r.uuid=t,r.loaded=0,r.base_url=i,r.queue=[],m.rht=function(){r.queue.push(arguments)};e=a.getElementsByTagName('script')[0],c=a.createElement('script');c.async=!0,c.src=i+'/widget/'+t+'.js',e.parentNode.insertBefore(c,e)}(window,document,'https://app.referralhero.com','MFe4b0315b5b');</script>  <!-- end ReferralHero code -->  
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/multi_form_page.html.erb
<h1>Multi-Form Page</h1>

<%= form_tag(process_forms_path) do %>
  <h2>Form 1</h2>
  <label for="form1_name">Name:</label>
  <%= text_field_tag 'form1_name' %><br>
  <label for="form1_email">Email:</label>
  <%= email_field_tag 'form1_email' %><br>
  <%= submit_tag 'Submit' %>
<% end %>

<%= form_tag(process_forms_path) do %>

  <h2>Form 2</h2>
  <label for="form2_name">Name:</label>
  <%= text_field_tag 'form2_name' %><br>
  <label for="form2_email">Email:</label>
  <%= email_field_tag 'form2_email' %><br>
  <%= submit_tag 'Submit' %>
<% end %>

<%= form_tag(process_forms_path) do %>

  <h2>Form 3</h2>
  <label for="form3_name">Name:</label>
  <%= text_field_tag 'form3_name' %><br>
  <label for="form3_email">Email:</label>
  <%= email_field_tag 'form3_email' %><br>

  <%= submit_tag 'Submit' %>
<% end %>